// File generated by FlutterFire CLI.
// This is a placeholder configuration file.
// To generate the proper configuration for your Firebase project, run:
// flutterfire configure

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqb6COPRRgXfMfgSfkOWd-9nGDWRHFd1U',
    appId: '1:451817571128:web:dummy',
    messagingSenderId: '451817571128',
    projectId: 'plan-b-canales',
    authDomain: 'plan-b-canales.firebaseapp.com',
    storageBucket: 'plan-b-canales.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqb6COPRRgXfMfgSfkOWd-9nGDWRHFd1U',
    appId: '1:451817571128:android:71bab8b560c807285c37cd',
    messagingSenderId: '451817571128',
    projectId: 'plan-b-canales',
    storageBucket: 'plan-b-canales.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqb6COPRRgXfMfgSfkOWd-9nGDWRHFd1U',
    appId: '1:451817571128:ios:dummy',
    messagingSenderId: '451817571128',
    projectId: 'plan-b-canales',
    storageBucket: 'plan-b-canales.firebasestorage.app',
    iosBundleId: 'com.example.pivote_studio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqb6COPRRgXfMfgSfkOWd-9nGDWRHFd1U',
    appId: '1:451817571128:ios:dummy',
    messagingSenderId: '451817571128',
    projectId: 'plan-b-canales',
    storageBucket: 'plan-b-canales.firebasestorage.app',
    iosBundleId: 'com.example.pivote_studio',
  );
}
